import './globals.css'
import { Inter } from 'next/font/google'

import { Header } from '@/app/components/Header'
import { Navbar } from '@/app/components/Navbar'
import { Footer } from '@/app/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 ${inter.className}`}>
        <div className='bg-slate-200'>
          <Header />
          <Navbar />
        </div>
        <div className='h-full'>
          {children}
        </div>        
        <Footer />
      </body>
    </html>
  )
}
